### PR TITLE
Transition to go modules for dep management

### LINKED ISSUE #82: Move from dep to go modules
With Go 1.14, modules are the standard for dependency management.

### PR DESCRIPTION
**Pull request by shawn-hurley**
* remove Gopkg.{lock/toml}
* Update Makefile to pull controller-gen correctly and use it
* Updated module names for kubevirt imports
* Updated client.List calls to conform to correct dynamic client interface.

fixes #82

### CODE REVIEW

**Review by jortel — APPROVED** [review]
LGTM

**Comment by aufi** [comment]
Looks good :+1:

**Review by fdupont-redhat — APPROVED** [review]
LGTM

**Comment by fdupont-redhat** [comment]
I couldn't manage to resolve the conflicts, so I create a new branch from master, applied your changes and submitted #126. Now that #126 is merged, I'm closing this one. Thanks @shawn-hurley for doing the hard work.

**Pull request closed without merging**
