### PR TITLE
Report Migration progress to Step Phase

### PR DESCRIPTION
**Pull request by aufi**
Updating migration Steps with Phase names providing migration progress
in Forklift UI.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2047460

### CODE REVIEW

**Comment by aufi** [comment]
image

**Comment by aufi** [comment]
Example screencast from Forklift UI with changes in this PR:

mig_speedup

**Review by mansam — APPROVED** [review]
Looks great!

**Comment by jortel** [comment]
back-ported to 2.3.

**Pull request merged**
